name: fridge_finds_final
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  intl: ^0.18.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/image/spaghetti_carbonara.jpg
    - lib/image/chicken_alfredo.jpg
    - lib/image/vegetarian_tacos.jpg
    - lib/image/beef_stew.jpg
    - lib/image/chicken_curry.jpg
    - lib/image/veggie_stir_fry.jpg

